spring:
  datasource:
#    url: jdbc:mysql://127.0.0.1:3306/daotable?useUnicode=true&characterEncoding=UTF-8
#    username: root
#    password: 123
    url: jdbc:mysql://127.0.0.1:3306/xinx?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    max-idle: 10
    max-wait: 1000
    min-idle: 5
    initial-size: 5
 # \u63A7\u5236\u53F0\u989C\u8272\u63A7\u5236
    output.ansi.enabled: always
#    mvc.static-path-pattern: /resources/**

mybatis:
  mapperLocations: classpath:com/libei/dao/mysql/mapper/*.xml
  typeAliasesPackage: com.libei.domain.entity
  configuration:
    map-underscore-to-camel-case: true

server:
  port: 8080
  context-path: /libei
  session:
    timeout: 10
  tomcat:
      uri-encoding: UTF-8